### ISSUE TITLE
Games don't load.

### ISSUE THREAD

**Issue by Ultimateyoshijes** [tswilliamson/prizoop#7] opened 2019-09-08 15:30 UTC
Hello ya'll

I've been having an issue with loading the games I downloaded to Prizoop. 

When I press start it says:
Loading file "game name"
GB ROM name"game name"
MBC type: ROM_MBG1
RAM type: RAM_NONE
Num ROM banks: 4
No save file, not battery backed

When I try to another game it says the same and when I press F6 again I get this error:

System ERROR
REBOOT : EXIT
INITIALIZE : EXE
TLB ERROR
TARGET= 6C208C30
PC = 00000027

I'm using the FX-CG50 to play the games.
Does anybody know the solution to this problem?

**Comment by Game4all** [comment] 2019-09-08 16:48
Duplicate of #6 
Please look at issue #6 and see the proposed workarround

**Comment by Ultimateyoshijes** [comment] 2019-09-08 16:51
Yeah I tried that and it didn’t work unfortunately

**Comment by Game4all** [comment] 2019-09-08 17:09
Could you please details about the ROM you tried to load

**Comment by Ultimateyoshijes** [comment] 2019-09-08 17:12
Well it’s all three of them 
Pokémon blue.GB
Super Mario world.GB
Super Mario bros deluxe.GBA

**Comment by foss63** [comment] 2019-11-02 17:24
I have the same problem with the same games but on the CASIO graph 90+e. If someone can help me, thanks.

**Comment by Game4all** [comment] 2019-11-02 17:45
Have you seen and tried  the workarround proposed in https://github.com/tswilliamson/prizoop/issues/6#issuecomment-482735854 ? (Shoud work for a Graph90+E as it did for me)

**Comment by tswilliamson** [comment] 2019-11-14 17:06
As stated in the readme: "The filenames for these files should be simple and less than 12 characters, such as MyGame.gbc."

**Closed by tswilliamson** 2019-11-14 17:06 UTC

**Comment by foss63** [comment] 2019-11-14 19:22
Thanks it works so Nice!
